# LAYTON3
OPCODE_LOAD_ASSET                   = b'\xf2\x03'
OPCODE_DEFINITION_FRAME_START       = b'\xfc\x03'
OPCODE_DEFINITION_FRAME_END         = b'\xfd\x03'
OPCODE_DEFINITION_FRAME_MIX_CONTENT = b'\xfe\x03'
OPCODE_DEFINITION_ANIM_START        = b'\x06\x04'
OPCODE_DEFINITION_ANIM_END          = b'\x07\x04'
OPCODE_DEFINITION_ANIM_MIX_FRAME    = b'\x08\x04'